# **Introduction to PyTorch - Tensor Operations and Basics**
---

## **Overview**
* This notebook covers the basics of PyTorch, focusing on tensor creation, manipulation, and fundamental operations. Each section explains the purpose of the operations, where they are used, and their relevance to deep learning workflows.
---

## **Check PyTorch Version and Device Availability**
>This cell verifies the installed PyTorch version and determines whether a GPU is available for computations. If a GPU is present, it displays its name; otherwise, it defaults to the CPU. This is a crucial first step for optimizing model training and performance.

In [1]:
import torch

In [2]:
print(torch.__version__)

2.5.1+cu121


In [4]:
if torch.cuda.is_available():
    print(f"Using GPU: {torch.cuda.get_device_name(0)}.")
else:
    print("GPU not available. Using CPU.")

GPU not available. Using CPU.


---
## **Tensor Creation**
>Tensors are the basic data structures in PyTorch, analogous to NumPy arrays but optimized for GPU computations. This cell demonstrates how to create tensors with specific initializations.

In [162]:
# Creating basic tensors
basic_tensor = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(f"Basic Tensor:\n{basic_tensor}\n\n")

# Empty tensor (uninitialized values)
empty_tensor = torch.empty(2, 3)
print(f"Empty Tensor:\n{empty_tensor}\n\n")

# Tensors filled with zeros and ones
zeros_tensor = torch.zeros(2, 3)
print(f"Zeros Tensor:\n{zeros_tensor}\n\n")

ones_tensor = torch.ones(2, 3)
print(f"Ones Tensor:\n{ones_tensor}\n\n")

# Random tensor
random_tensor = torch.rand(2, 3)
print(f"Random Tensor:\n{random_tensor}")

Basic Tensor:
tensor([[1, 2, 3],
        [4, 5, 6]])


Empty Tensor:
tensor([[-8.6965e-28,  4.4948e-41, -2.9332e-34],
        [ 3.1608e-41,  4.0481e-01,  9.1996e-01]])


Zeros Tensor:
tensor([[0., 0., 0.],
        [0., 0., 0.]])


Ones Tensor:
tensor([[1., 1., 1.],
        [1., 1., 1.]])


Random Tensor:
tensor([[0.3699, 0.5012, 0.6380],
        [0.0111, 0.4356, 0.1696]])


---
## **Tensor Creation with Specific Patterns**
>This cell introduces common tensor creation patterns, including seeded random values, ranges, and constant values. These methods are useful for initializing weights and building test cases.

In [163]:
# Setting a random seed for reproducibility
torch.manual_seed(110)
seeded_tensor = torch.rand(2, 3)
print(f"Seeded Random Tensor:\n{seeded_tensor}\n\n")

# Range-based tensors
range_tensor = torch.arange(10)  # Sequence from 0 to 9
print(f"Range Tensor:\n{range_tensor}\n\n")

linspace_tensor = torch.linspace(0, 1, steps=5)  # 5 evenly spaced points between 0 and 1
print(f"Linspace Tensor:\n{linspace_tensor}\n\n")

# Identity matrix
identity_tensor = torch.eye(3)
print(f"Identity Tensor:\n{identity_tensor}\n\n")

# Tensor with constant values
full_tensor = torch.full((3, 3), 5)
print(f"Tensor with All Elements as 5:\n{full_tensor}")

Seeded Random Tensor:
tensor([[0.7111, 0.0904, 0.5646],
        [0.7994, 0.1508, 0.6337]])


Range Tensor:
tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


Linspace Tensor:
tensor([0.0000, 0.2500, 0.5000, 0.7500, 1.0000])


Identity Tensor:
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


Tensor with All Elements as 5:
tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


---
## **Tensors with the Same Shape**
>These functions are used to create tensors with the same shape as an existing tensor, which is helpful for initializing or modifying model parameters.

In [165]:
# Create tensors matching the shape of an existing tensor
zeros_like_tensor = torch.zeros_like(basic_tensor)
print(f"Zeros Like Tensor:\n{zeros_like_tensor}\n\n")

ones_like_tensor = torch.ones_like(basic_tensor)
print(f"Ones Like Tensor:\n{ones_like_tensor}\n\n")

random_like_tensor = torch.rand_like(basic_tensor, dtype=torch.float32)
print(f"Random Like Tensor:\n{random_like_tensor}")

Zeros Like Tensor:
tensor([[0, 0, 0],
        [0, 0, 0]])


Ones Like Tensor:
tensor([[1, 1, 1],
        [1, 1, 1]])


Random Like Tensor:
tensor([[0.4826, 0.9588, 0.1291],
        [0.5870, 0.3136, 0.7080]])


---
## **Tensor Data Types and Conversions**
>This demonstrates how to specify and convert tensor data types, which is critical for ensuring compatibility between operations in deep learning models.

In [166]:
# Specifying data types
int_tensor = torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.int32)
print(f"Integer Tensor:\n{int_tensor}\n\n")

float_tensor = int_tensor.to(dtype=torch.float32)
print(f"Float Tensor:\n{float_tensor}")

Integer Tensor:
tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)


Float Tensor:
tensor([[1., 2., 3.],
        [4., 5., 6.]])


---
## **Basic Arithmetic Operations**
>Arithmetic operations are performed element-wise and are foundational to defining custom loss functions, scaling, or data transformations.

In [167]:
# Creating sample tensors
x1 = torch.rand(2, 3)

# Arithmetic operations
print(f"x1 + 2:\n{x1 + 2}\n\n")
print(f"x1 - 2:\n{x1 - 2}\n\n")
print(f"x1 * 2:\n{x1 * 2}\n\n")
print(f"x1 / 2:\n{x1 / 2}\n\n")
print(f"x1 ** 2:\n{x1 ** 2}")

x1 + 2:
tensor([[2.0611, 2.7027, 2.1919],
        [2.1905, 2.3536, 2.0240]])


x1 - 2:
tensor([[-1.9389, -1.2973, -1.8081],
        [-1.8095, -1.6464, -1.9760]])


x1 * 2:
tensor([[0.1223, 1.4055, 0.3838],
        [0.3810, 0.7072, 0.0481]])


x1 / 2:
tensor([[0.0306, 0.3514, 0.0960],
        [0.0952, 0.1768, 0.0120]])


x1 ** 2:
tensor([[0.0037, 0.4938, 0.0368],
        [0.0363, 0.1250, 0.0006]])


---
## **Comparison Operations**
>Comparison operators return boolean tensors, which are useful for masking or filtering specific elements in deep learning workflows.

In [168]:
# Creating sample tensors
tensor_a = torch.randint(0, 10, (3, 3))
tensor_b = torch.randint(0, 10, (3, 3))

# Comparison operators
print(f"tensor_a > tensor_b:\n{tensor_a > tensor_b}\n\n")
print(f"tensor_a == tensor_b:\n{tensor_a == tensor_b}\n\n")
print(f"tensor_a <= tensor_b:\n{tensor_a <= tensor_b}")

tensor_a > tensor_b:
tensor([[False,  True, False],
        [False,  True,  True],
        [ True,  True,  True]])


tensor_a == tensor_b:
tensor([[ True, False, False],
        [False, False, False],
        [False, False, False]])


tensor_a <= tensor_b:
tensor([[ True, False,  True],
        [ True, False, False],
        [False, False, False]])


---
## **Matrix Operations**
>Matrix and vector operations form the backbone of deep learning, as they represent computations in fully connected and convolutional layers.

In [176]:
# Matrix operations
matrix_a = torch.randint(0, 10, (2, 3))
matrix_b = torch.randint(0, 10, (3, 2))

# Matrix multiplication
matrix_result = torch.matmul(matrix_a, matrix_b)
print(f"Matrix Multiplication Result:\n{matrix_result}\n\n")

# Vector operations
vector_a = torch.tensor([1, 2, 3])
vector_b = torch.tensor([4, 5, 6])

dot_product = torch.dot(vector_a, vector_b)
print(f"Dot Product:\n{dot_product}\n\n")

cross_product = torch.cross(vector_a, vector_b)
print(f"Cross Product:\n{cross_product}")

# Determinant and inverse
square_matrix = torch.randint(size=(3, 3), low=1, high=10, dtype=torch.float32)

determinant = torch.det(square_matrix)  # Determinant
inverse = torch.inverse(square_matrix)  # Inverse of a matrix

print(f"Square Matrix:\n{square_matrix}\n\n")
print(f"Determinant:\n{determinant}\n\n")
print(f"Inverse:\n{inverse}")

Matrix Multiplication Result:
tensor([[61, 38],
        [71, 17]])


Dot Product:
32


Cross Product:
tensor([-3,  6, -3])
Square Matrix:
tensor([[4., 9., 4.],
        [3., 3., 5.],
        [9., 1., 4.]])


Determinant:
228.99998474121094


Inverse:
tensor([[ 0.0306, -0.1397,  0.1441],
        [ 0.1441, -0.0873, -0.0349],
        [-0.1048,  0.3362, -0.0655]])


---
## **Statistical Operations**
>Statistical functions are critical for analyzing data distributions, computing metrics, and applying normalization.

In [170]:
# Statistical operations
stat_tensor = torch.randint(0, 10, (2, 3), dtype=torch.float32)

print(f"Sum:\n{torch.sum(stat_tensor)}\n\n")
print(f"Mean:\n{torch.mean(stat_tensor)}\n\n")
print(f"Median:\n{torch.median(stat_tensor)}\n\n")
print(f"Standard Deviation:\n{torch.std(stat_tensor)}\n\n")
print(f"Max Value:\n{torch.max(stat_tensor)}\n\n")
print(f"Min Value:\n{torch.min(stat_tensor)}")

Sum:
27.0


Mean:
4.5


Median:
1.0


Standard Deviation:
3.987480401992798


Max Value:
9.0


Min Value:
1.0


---
## **Tensor Reshaping and Flattening**
>Reshaping allows tensors to fit specific model architectures, while flattening is commonly used in transitioning from convolutional to fully connected layers.

In [171]:
# Reshaping tensors
tensor_2d = torch.rand(4, 4)

reshaped_tensor = tensor_2d.reshape(2, 2, 4)
print(f"Reshaped Tensor:\n{reshaped_tensor}\n\n")

flattened_tensor = tensor_2d.flatten()
print(f"Flattened Tensor:\n{flattened_tensor}")

Reshaped Tensor:
tensor([[[0.8859, 0.0505, 0.2996, 0.7855],
         [0.7175, 0.7284, 0.8830, 0.8519]],

        [[0.9472, 0.5648, 0.5515, 0.6643],
         [0.2953, 0.6694, 0.5809, 0.8117]]])


Flattened Tensor:
tensor([0.8859, 0.0505, 0.2996, 0.7855, 0.7175, 0.7284, 0.8830, 0.8519, 0.9472,
        0.5648, 0.5515, 0.6643, 0.2953, 0.6694, 0.5809, 0.8117])


---
## **Cloning and In-place Operations**
>Cloning ensures that a copy of the tensor is created for independent manipulation, while in-place operations directly modify the original tensor.

In [172]:
# Cloning and in-place operations
tensor_original = torch.rand(2, 3)
tensor_clone = tensor_original.clone()

print(f"Original Tensor ID: {id(tensor_original)}\n\n")
print(f"Cloned Tensor ID: {id(tensor_clone)}\n\n")

# In-place addition
tensor_original.add_(tensor_clone)
print(f"In-place Added Tensor:\n{tensor_original}")

Original Tensor ID: 137764237015248


Cloned Tensor ID: 137764237004048


In-place Added Tensor:
tensor([[0.1132, 1.0897, 1.4572],
        [1.5520, 0.3437, 1.1513]])


---
## **Advanced Tensor Operations**
>These operations are essential for advanced linear algebra computations, especially in tasks like solving systems of equations or computing eigenvalues.

In [173]:
# Transpose and determinant
square_tensor = torch.rand(3, 3)

transposed = torch.transpose(square_tensor, 0, 1)
print(f"Transposed Tensor:\n{transposed}\n\n")

determinant = torch.det(square_tensor)
print(f"Determinant:\n{determinant}\n\n")

# Advanced element-wise operations
tensor_a = torch.tensor([-1.0, -2.0, -3.0])

absolute_values = torch.abs(tensor_a)  # Absolute values
print(f"Absolute Values:\n{absolute_values}\n\n")

tensor_b = torch.tensor([1.9, 2.7, 3.2])
rounded = torch.round(tensor_b)  # Rounding values
floored = torch.floor(tensor_b)  # Floor operation
ceiled = torch.ceil(tensor_b)    # Ceiling operation

print(f"Rounded:\n{rounded}\n\n")
print(f"Floored:\n{floored}\n\n")
print(f"Ceiled:\n{ceiled}\n\n")

# Clamp values within a range
clamped = torch.clamp(tensor_b, min=2.0, max=3.0)
print(f"Clamped Tensor (2.0 to 3.0):\n{clamped}")

Transposed Tensor:
tensor([[0.7482, 0.9570, 0.4607],
        [0.8451, 0.0871, 0.8130],
        [0.8652, 0.3297, 0.3212]])


Determinant:
0.32738903164863586


Absolute Values:
tensor([1., 2., 3.])


Rounded:
tensor([2., 3., 3.])


Floored:
tensor([1., 2., 3.])


Ceiled:
tensor([2., 3., 4.])


Clamped Tensor (2.0 to 3.0):
tensor([2.0000, 2.7000, 3.0000])


---
## **Activation Functions**
>Activation functions introduce non-linearity into deep learning models:
* ReLU: Replaces negatives with 0.
* Sigmoid: Compresses output between (0, 1).
* Tanh: Compresses output between (-1, 1).
* Softmax: Converts outputs into probabilities.


In [174]:
# Activation functions
input_values = torch.linspace(-5, 5, steps=10)

relu_output = torch.relu(input_values)  # Rectified Linear Unit
sigmoid_output = torch.sigmoid(input_values)  # Sigmoid
tanh_output = torch.tanh(input_values)  # Hyperbolic tangent
softmax_output = torch.softmax(input_values, dim=0)  # Softmax along a dimension

print(f"Input Values:\n{input_values}\n\n")
print(f"ReLU Activation:\n{relu_output}\n\n")
print(f"Sigmoid Activation:\n{sigmoid_output}\n\n")
print(f"Tanh Activation:\n{tanh_output}\n\n")
print(f"Softmax Activation:\n{softmax_output}")

Input Values:
tensor([-5.0000, -3.8889, -2.7778, -1.6667, -0.5556,  0.5556,  1.6667,  2.7778,
         3.8889,  5.0000])


ReLU Activation:
tensor([0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.5556, 1.6667, 2.7778, 3.8889,
        5.0000])


Sigmoid Activation:
tensor([0.0067, 0.0201, 0.0585, 0.1589, 0.3646, 0.6354, 0.8411, 0.9415, 0.9799,
        0.9933])


Tanh Activation:
tensor([-0.9999, -0.9992, -0.9923, -0.9311, -0.5047,  0.5047,  0.9311,  0.9923,
         0.9992,  0.9999])


Softmax Activation:
tensor([3.0455e-05, 9.2514e-05, 2.8103e-04, 8.5370e-04, 2.5933e-03, 7.8778e-03,
        2.3931e-02, 7.2695e-02, 2.2083e-01, 6.7082e-01])


---
## **In-Place Operations**
>In-place operations save memory but modify the original tensor, which can be risky if gradients are being tracked. The underscore at the end of the function name indicates an in-place operation.

In [177]:
# In-place operations
tensor_a = torch.rand(2, 3)
tensor_b = torch.rand(2, 3)

tensor_a.add_(tensor_b)  # In-place addition
print(f"In-place Addition Result:\n{tensor_a}\n\n")

tensor_a.relu_()  # In-place ReLU activation
print(f"In-place ReLU Activation:\n{tensor_a}")

In-place Addition Result:
tensor([[1.5029, 1.0747, 1.5714],
        [0.8316, 1.2008, 0.6204]])


In-place ReLU Activation:
tensor([[1.5029, 1.0747, 1.5714],
        [0.8316, 1.2008, 0.6204]])


---
## **Squeeze and Unsqueeze Operations**
>- `unsqueeze()` adds a new dimension of size 1 at the specified index.
- `squeeze()` removes dimensions of size 1, which is useful for reducing the rank of tensors after certain operations (e.g., after a convolution).

In [178]:
# Squeeze and Unsqueeze
tensor = torch.rand(1, 20, 1, 10)

# Unsqueeze adds a new dimension at position 0
unsqueezed_tensor = tensor.unsqueeze(0)  # Adds a batch dimension
print(f"Unsqueezed Tensor Shape:\n{unsqueezed_tensor.shape}\n\n")

# Squeeze removes dimensions of size 1
squeezed_tensor = tensor.squeeze(0)  # Removes the batch dimension (size 1)
print(f"Squeezed Tensor Shape:\n{squeezed_tensor.shape}")

Unsqueezed Tensor Shape:
torch.Size([1, 1, 20, 1, 10])


Squeezed Tensor Shape:
torch.Size([20, 1, 10])


---
## **NumPy Interoperability**
>Interoperability between PyTorch and NumPy ensures compatibility with Python libraries. This is especially useful for scientific computing and visualizations.

In [179]:
import numpy as np

In [180]:
# Conversion between PyTorch tensors and NumPy arrays
torch_to_numpy = torch.tensor([1.0, 2.0, 3.0]).numpy()  # Tensor to NumPy
numpy_to_torch = torch.from_numpy(np.array([4.0, 5.0, 6.0]))  # NumPy to Tensor

print(f"Converted to NumPy:\n{torch_to_numpy}\n\n")
print(f"Converted to PyTorch Tensor:\n{numpy_to_torch}")

Converted to NumPy:
[1. 2. 3.]


Converted to PyTorch Tensor:
tensor([4., 5., 6.], dtype=torch.float64)
